### ISSUE TITLE
인터뷰 스터디 - 210923 목요일 19:00까지 주제 선정 및 발표 자료 공유

### ISSUE THREAD

**Issue by okstring** [iOS-study-delicato/Interview-Study#5]
발표자료 공유는 선택입니다

**Comment by JUNGYUN-Daegu** [comment]
`UINavigationController 의 역할이 무엇인지 설명하시오.`를 준비해 오겠습니다😁

**Comment by okstring** [comment]
`RxSwift에서 Hot Observable과 Cold Observable의 차이를 설명하시오.` 를 준비해오겠습니다💡

**Comment by okstring** [comment]
[https://velog.io/@okstring/Hot-vs-Cold-Observable-간략하게-이해하기](https://velog.io/@okstring/Hot-vs-Cold-Observable-간략하게-이해하기)

**Comment by 1song2** [comment]
`고차 함수가 무엇인지 설명하시오.`를 공부해오겠습니다 :)

**Comment by Lia316** [comment]
`Foundation Kit은 무엇이고 포함되어 있는 클래스들은 어떤 것이 있는지 설명하시오.` 를 준비해오겠습니다

**Comment by HongzCloud** [comment]
In - active 상태가 되는 시나리오를 설명하시오. 를 준비해오겠습니다.

**Comment by 1song2** [comment]
발표 자료: https://github.com/1song2/interview-cheat-sheet/blob/main/higher-order-function.md
