### ISSUE TITLE
인터뷰 스터디 - 210930 목요일 19:00까지 주제 선정 및 발표 자료 공유(WWDC, 면접 질문 병행)

### ISSUE THREAD

**Issue by okstring** [iOS-study-delicato/Interview-Study#6]

**Comment by okstring** [comment]
`Concurrent Programming With GCD in Swift 3` 를 공부하겠습니다 :)

**Comment by 1song2** [comment]
`shallow copy와 deep copy의 차이점을 설명하시오.`에 대해 공부해오겠습니다✏️

**Comment by JUNGYUN-Daegu** [comment]
`특정 객체를 autorelease 하기 위해 필요한 사항과 과정을 설명하시오.`
`Autorelease Pool을 사용해야 하는 상황을 두 가지 이상 예로 들어 설명하시오.`
를 합쳐서 autoRelease 키워드에 대해 공부해 오겠습니다~!

**Comment by okstring** [comment]
https://velog.io/@okstring/번역-Concurrent-Programming-With-GCD-in-Swift-3
